site_name: DicasDeEstagio - G5
#site_author: Mateus Villela
site_description: Site voltado para a documentação do Grupo 5 de Arquitetura e Desenvolvimento de Software - 2025.2
repo_url: https://github.com/UnBArqDsw2025-2-Turma02/2025.2-T02_G5_DicasDeEstagio_Entrega01
repo_name: 2025.2-DicasDeEstagio-Entrega1

theme:
  name: material
  logo: 'assets/imgs/LogoPrincipalG5.png'
  favicon: 'assets/imgs/LogoPrincipalG5.png'

  palette:
    - scheme: default
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Home: docs/home.md
  - Base:
    - Introdução: docs/Base/Base.md
    - Participações: docs/Base/ParticipacoesBase.md
    - Artefatos Generalistas: docs/Base/Artefatos-generalistas/ArtefatosGeneralistas.md
    - BPMN: docs/Base/BPMN/ModelagemBPMN.md
    - Design Sprint:
      - Decide: docs/Base/Design-sprint/Decide.md
      - Design Sprint: docs/Base/Design-sprint/DesignSprint.md
      - Prototype: docs/Base/Design-sprint/Prototype.md
      - Sketch: docs/Base/Design-sprint/Sketch.md
      - Unpack: docs/Base/Design-sprint/Unpack.md
      - Validate: docs/Base/Design-sprint/Validate.md
    - Iniciativas Extras:
      - Gravações: docs/Base/Iniciativas-extras/Gravacoes.md
      - Iniciativas Extras: docs/Base/Iniciativas-extras/IniciativasExtras.md
      - Atas de Reunião: docs/Base/Iniciativas-extras/Atas-de-reuniao/
      - Planejamento:
        - Cronograma Executado: docs/Base/Iniciativas-extras/Planejamento/CronogramaExecutado.md
        - Cronograma Planejado: docs/Base/Iniciativas-extras/Planejamento/CronogramaPlanejado.md
        - Ferramentas: docs/Base/Iniciativas-extras/Planejamento/Ferramentas.md
        - Heatmap Disponibilidade: docs/Base/Iniciativas-extras/Planejamento/HeatmapDisponibilidade.md
        - Políticas de Repositório:
          - Política de Branches: docs/Base/Iniciativas-extras/Planejamento/Politicas-de-repositorio/PoliticaBranches.md
          - Política de Commits: docs/Base/Iniciativas-extras/Planejamento/Politicas-de-repositorio/PoliticaCommits.md
  - Projeto:
    - Projeto: docs/Projeto/Projeto.md

        
markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
#  - mkdocs-pdf

extra_css:
  - assets/css/custom.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js