site_name: DicasDeEstagio - G5
#site_author: Mateus Villela
site_description: Site voltado para a documentação do Grupo 5 de Arquitetura e Desenvolvimento de Software - 2025.2
repo_url: https://github.com/UnBArqDsw2025-2-Turma02/G5_DicasDeEstagio_Entrega01
repo_name: 2025.2-DicasDeEstagio-Entrega1

theme:
  name: material
  logo: 'assets/imgs/LogoPrincipalG5.png'
  favicon: 'assets/imgs/LogoPrincipalG5.png'

  palette:
    - scheme: default
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Home: home.md
  
  #- Gravações:
    #- Entregas: 'gravacoes/entregas/grav-entrega.md'
    #- Reuniões: 'gravacoes/reunioes/grav-reunioes.md'
    #- Ata de reunião 10/04/2025:
    
  # - Pré-Rastreabilidade:
  #   - Rich-Picture: 'pre-rastreabilidade/rich-picture.md' 
  
  #- Planejamento:
  #  - Políticas do Repositório:
  #      - Branches: 'planejamento/politicas_repositorio/politica_branches.md'
  #      - Commits:  'planejamento/politicas_repositorio/politica_commits.md'
  #  - Cronograma:              'planejamento/cronograma.md'
  #  - Cronograma Executado:    'planejamento/cronograma-executado.md'
  #  - Ferramentas:             'planejamento/ferramentas.md'
  #  - Heatmap:                 'planejamento/heatmap.md'
  #  - Aplicativo: 'planejamento/lista-de-apps-avaliados.md'
  #  - Termo de Uso:            'planejamento/termo-de-uso.md'

  - Projetos: docs/Projeto/Projeto.md
  - Base:
      - 1. Desenho de Software (Base): docs/Base/1.Base.md
      - 1.1. Design Sprint: docs/Base/1.1.DesignSprint.md
      - 1.2. Artefato Generalista: docs/Base/1.2.ArtefatoGeneralista.md
      - 1.3. Modelagem BPMN: docs/Base/1.3.ModelagemBPMN.md
      - 1.4. Participações - Base: docs/Base/1.4.ParticipacoesBase.md
      - 1.5. Iniciativas Extras - Base: docs/Base/1.5.IniciativasExtras.md

        
markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
#  - mkdocs-pdf

extra_css:
  - assets/css/custom.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js