site_name: DicasDeEstagio - G5
#site_author: Mateus Villela
site_description: Site voltado para a documentação do Grupo 5 de Arquitetura e Desenvolvimento de Software - 2025.2
repo_url: https://github.com/UnBArqDsw2025-2-Turma02/2025.2-T02_G5_DicasDeEstagio_Entrega01
repo_name: 2025.2-DicasDeEstagio-Entrega1

theme:
  name: material
  logo: 'assets/imgs/LogoPrincipalG5.png'
  favicon: 'assets/imgs/LogoPrincipalG5.png'

  palette:
    - scheme: default
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      primary: "#00543C"   # Verde Pantone 348
      accent: "#193A6A"    # Azul Pantone 654
      auxiliary: "#FFD600" # Amarelo Pantone 012C (contraste)
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Início: README.md
  - Base:
    - Introdução: Base/Base.md
    - Participações: Base/ParticipacoesBase.md
    - Artefatos Generalistas:
      - Visão geral: Base/Artefatos-generalistas/ArtefatosGeneralistas.md
      - Diagrama Causa-Efeito: Base/Artefatos-generalistas/CausaEfeito.md
    - BPMN: Base/BPMN/ModelagemBPMN.md
    - Design Sprint:
      - Decide: Base/Design-sprint/Decide.md
      - Design Sprint: Base/Design-sprint/DesignSprint.md
      - Prototype: Base/Design-sprint/Prototype.md
      - Sketch: Base/Design-sprint/Sketch.md
      - Unpack: Base/Design-sprint/Unpack.md
      - Validate: Base/Design-sprint/Validate.md
    - Iniciativas Extras:
      - Gravações: Base/Iniciativas-extras/Gravacoes.md
      - Iniciativas Extras: Base/Iniciativas-extras/IniciativasExtras.md
      - Atas de Reunião:
        - Ata 1 - 24/08/2025: Base/Iniciativas-extras/Planejamento/ata1.md
        - Ata 2 - 27/08/2025: Base/Iniciativas-extras/Planejamento/ata2.md
        - Ata 3 - 02/09/2025: Base/Iniciativas-extras/Planejamento/ata3.md
      - Planejamento:
        - Cronograma Executado: Base/Iniciativas-extras/Planejamento/CronogramaExecutado.md
        - Cronograma Planejado: Base/Iniciativas-extras/Planejamento/CronogramaPlanejado.md
        - Ferramentas: Base/Iniciativas-extras/Planejamento/Ferramentas.md
        - Heatmap Disponibilidade: Base/Iniciativas-extras/Planejamento/HeatmapDisponibilidade.md
        - Políticas de Repositório:
          - Política de Branches: Base/Iniciativas-extras/Planejamento/Politicas-de-repositorio/PoliticaBranches.md
          - Política de Commits: Base/Iniciativas-extras/Planejamento/Politicas-de-repositorio/PoliticaCommits.md

        
markdown_extensions:
  - pymdownx.details
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
#  - mkdocs-pdf

extra_css:
  - assets/css/custom.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js